name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/homepage:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/homepage:${{ github.sha }}

    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        tags: tag:github-actions

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_TAILSCALE_IP }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_PORT || 22 }}
        script: |
          # Pull latest image
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/homepage:latest

          # Stop existing container if running
          docker stop homepage || true
          docker rm homepage || true

          # Start new container
          docker run -d \
            --name homepage \
            --restart unless-stopped \
            -p 80:80 \
            -p 443:443 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/homepage:latest

          # Clean up old images
          docker image prune -f